apiVersion: v2
name: cloud-site-chart
description: Empty chart with dependency  on totara-argocd chart
type: application

version: "1.0"
appVersion: "18.2-20240126"

dependencies:
  - name: redis-ha
    version: 4.26.1
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled